version: "3.3"

services:
  db:
    image: mysql:8.0
    volumes:
      - ./docker/dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ROOT_USER: "root"
      MYSQL_DATABASE: "vila"
    restart: always
    networks:
      - default

  mensageria:
    container_name: service-rabbitmq
    image: rabbitmq:3.9.7-management
    ports:
      - "5672:5672"
      - "15672:15672"
      - "45806:15672"
    restart: always
    environment:
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
    networks:
      - default

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.57.0/24